### ISSUE TITLE
Allow Draggable positioning based on grab point rather than midpoint

### ISSUE THREAD

**Issue by jevogel** [kutlugsahin/react-smooth-dnd#11]
If you have a very long draggable element, it can be impossible to drop it into a container that is too high up on the page if the drag handle is at the top of the draggable element. It would be nice if there was an option to set how the position is calculated. I also welcome any other solutions you might suggest.

**Comment by kutlugsahin** [comment]
I understand that you have a taller draggable than target container otherwise you could scroll to up so that mid point of draggable can be inside container. I recommend you to arrange the dimensions of containers and draggables so that it would feel more natural and possible to drop. If this wont work for you you can consider replacing the drag handle. All collision calculations are done regarding the mid points of draggables to simulate a physical drag and drop environment. It would be against the design and require a lot of refactor in code base to expose such option as you requested. Hope this helps. I am closing this issue. Feel free to discuss more. Cheers
