### ISSUE TITLE
Container doesn't accept className

### ISSUE THREAD

**Issue by alex35mil** [kutlugsahin/react-smooth-dnd#17]
Quick question: `Container` component accepts `style` prop but not `className`. Is this for a reason or it just doesn't get passed?

**Comment by kutlugsahin** [comment]
It does not accept classNames it manages its own classes internally. Actually if you want to style the container wrap it and add classes to the wrapper. the purpose that it accepts style is to enable editing dimensions of the box like min-height or padding-bottom. Normally container accept drops when the drag is inside its borders and by default its size will be determined according to the items inside but sometimes you want the box of container bigger than the child elements to accept the drop. So that's why you need to edit its style.  But again basically just style the wrapper to modify the appearance.

**Comment by alex35mil** [comment]
Gotcha. I wanted to set width on `Container` using CSS variable but I can move it on `Draggable` level since it accepts `className` prop so all good here. Thanks!

--
Also, unrelated question. I finished Reason bindings yesterday and literally just rendered dumb example w/o looking deep into complex cases. Is it possible to handle dnd of multiple selected items in the list?

**Comment by kutlugsahin** [comment]
Yes it is if they are consecutive. Just wrap the selected items in one Draggable so that they will be moved together.
