### ISSUE TITLE
Different payload?

### ISSUE THREAD

**Issue by Keyframe** [kutlugsahin/react-smooth-dnd#23]
Is it possible to have a payload inserted  that's different from the dragged item? Namely, copy drag from one list to another. I'd like to have one thing visible while copy dragging, but inserted something completely different.

**Comment by kutlugsahin** [comment]
I am not sure if I understand it correctly but yes you can set any payload in the getChildPayload function and do whatever you want to do with this payload on drop function.

**Comment by meganburtenshaw** [comment]
I am trying to do something similar. I am making a webform builder, where I have a menu of field types that I am copying/dragging onto the webform body. In the menu, all of the items are just the name of the field type (`<div>Input<div>,<div>Dropdown</div>` etc). But when they are copied and dropped onto the body of the webform, I want to render a different object (instead of `<div> Input </div>` I want the field to change to `<input type='text'/>` ). I've tried to modify the payload, but it doesn't seem to be working. Is there an example of how to change the payload to render a different object?
